name = "getcidworker2026828"
main = "worker.js"
compatibility_date = "2026-04-07"
compatibility_flags = ["nodejs_compat"]

# KV 命名空间绑定（必须绑定为 KV_LOGS）
kv_namespaces = [
  { binding = "KV_LOGS", id = "f5eeda55c2024352af023a26e5913480" }
]

# 环境变量默认值
[vars]
PAGE_SIZE = 20
TIMEZONE_OFFSET = 8
LOG_PASSWORD = "Xin123123..."

# 触发器规则
[triggers]
crons = []
